### PR TITLE
Added limitations of image stitching to README

### PR DESCRIPTION
**Pull request by dlebauer**

### CODE REVIEW

**Comment by dlebauer** [comment]
@weiqin61 the changes posted here can be added to the canopy cover extractor

**Comment by weiqin61** [comment]
A very first version of the README for Field Mosaic extractor.
1. recompile the document in the format given https://github.com/terraref/documentation/pull/164
2. add the info https://github.com/terraref/extractors-stereo-rgb/blob/82f6d982462e772e4c0bc402b222f6f64f046868/README.md to the extractor README.

**Comment by weiqin61** [comment]
4. add the links of the further discussions and citations
5. add the panned and proposed changes

removed all duplicate information from original README.md

**Comment by dlebauer** [comment]
@ZongyangLi or @pless could one of you please review the fieldmosaic/readme and complete the 'algorithm description' part? A brief summary with references should suffice.

**Pull request merged**
