### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Paheding**
Add the description of the RGB image quality enhancement extractor.

### CODE REVIEW

**Comment by dlebauer** [comment]
This is a great first step, but could you please add an algorithm description in the README under the canopy-cover-enhancement folder [extractors-stereo-rgb/canopy-cover-enhancement/readme.md](https://github.com/terraref/extractors-stereo-rgb/blob/master/canopy-cover-enhancement/readme.md) with sections such as authors, overview, algorithm description, quality statement, references, related issues, and further reading?

There are a few others that @ZongyangLi wrote, for example the canopy cover extractor in [extractors-stereo-rgb/canopycover/README](https://github.com/terraref/extractors-stereo-rgb/blob/master/canopycover/README.md).

**Comment by Paheding** [comment]
> please add more comprehensive algorithm description as canopy-cover-enhancement/readme.md

Yes, I have requested a full to create a folder in _extractors-stereo-rgb_. Once it's approved, I will write a comprehensive readme file, as well as uploading the extractor code, test code/image/results, etc.

**Comment by dlebauer** [comment]
the file already exists, doesn't it? Don't you have permission to update this file https://github.com/terraref/extractors-stereo-rgb/edit/master/canopy-cover-enhancement/readme.md?

**Comment by Paheding** [comment]
> the file already exists, doesn't it? Don't you have permission to update this file https://github.com/terraref/extractors-stereo-rgb/edit/master/canopy-cover-enhancement/readme.md?

It seems I do not have permission, I tried to update it but it asks me to create a pull request and approval. I have assigned you as a reviewer.

**Comment by Paheding** [comment]
@dlebauer My suggestion is that put this extractor into a separated folder (maybe named as "image_quality_enhancement") and then I can put upload related materials into the folder.

**Comment by dlebauer** [comment]
Sorry, I wasn't clear that this was a different extractor ... if it is, it makes sense to create a new directory.

**Comment by Paheding** [comment]
> Sorry, I wasn't clear that this was a different extractor ... if it is, it makes sense to create a new directory.

Thanks, I have created to a pull request to open a new folder.

**Pull request merged**
